TRADE_REGISTRY = {
    # === ORIGINAL 10 CORE TRADES ===
    "plumbing": {
        "name": "Plumbing",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "nextdoor"],
        "keywords": ["plumber", "plumbing", "pipe repair", "drain cleaning", "water heater",
                      "emergency plumber", "leak repair", "sewer line", "hydro jetting"],
        "avg_job_value": 450,
        "lead_cpl_ceiling": 35,
        "seasons": ["all"],
        "urgency_triggers": ["emergency", "burst pipe", "flood", "no water", "leak"],
        "best_platform": "google_maps",
        "conversion_rate": 0.12,
    },
    "hvac": {
        "name": "HVAC",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "facebook"],
        "keywords": ["hvac", "ac repair", "furnace", "heating", "air conditioning",
                      "heat pump", "duct cleaning", "thermostat", "hvac contractor"],
        "avg_job_value": 1200,
        "lead_cpl_ceiling": 55,
        "seasons": ["summer", "winter"],
        "urgency_triggers": ["no ac", "no heat", "broken furnace", "emergency hvac"],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.10,
    },
    "electrical": {
        "name": "Electrical",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "nextdoor"],
        "keywords": ["electrician", "electrical", "wiring", "panel upgrade", "lighting",
                      "outlet repair", "generator", "electrical contractor", "rewiring"],
        "avg_job_value": 600,
        "lead_cpl_ceiling": 40,
        "seasons": ["all"],
        "urgency_triggers": ["emergency electrician", "no power", "spark", "electrical fire"],
        "best_platform": "google_maps",
        "conversion_rate": 0.11,
    },
    "roofing": {
        "name": "Roofing",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "facebook"],
        "keywords": ["roofer", "roofing", "roof repair", "roof replacement", "shingles",
                      "roof leak", "metal roof", "flat roof", "storm damage"],
        "avg_job_value": 3500,
        "lead_cpl_ceiling": 85,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": ["roof leak", "storm damage", "hail damage", "missing shingles"],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.08,
    },
    "landscaping": {
        "name": "Landscaping",
        "platforms": ["google_maps", "yelp", "facebook", "nextdoor", "instagram"],
        "keywords": ["landscaper", "landscaping", "lawn care", "yard work", "sod",
                      "sprinkler", "hardscaping", "patio", "mulch", "tree service"],
        "avg_job_value": 800,
        "lead_cpl_ceiling": 30,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": [],
        "best_platform": "nextdoor",
        "conversion_rate": 0.15,
    },
    "painting": {
        "name": "Painting",
        "platforms": ["google_maps", "yelp", "homeadvisor", "angi", "nextdoor"],
        "keywords": ["painter", "painting", "house painter", "interior painting",
                      "exterior painting", "cabinet painting", "commercial painter"],
        "avg_job_value": 1500,
        "lead_cpl_ceiling": 45,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": [],
        "best_platform": "yelp",
        "conversion_rate": 0.13,
    },
    "general_contracting": {
        "name": "General Contracting",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "houzz"],
        "keywords": ["general contractor", "home renovation", "kitchen remodel",
                      "bathroom remodel", "basement finishing", "home addition",
                      "construction", "remodeling contractor"],
        "avg_job_value": 8000,
        "lead_cpl_ceiling": 120,
        "seasons": ["all"],
        "urgency_triggers": [],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.06,
    },
    "cleaning": {
        "name": "Cleaning",
        "platforms": ["google_maps", "yelp", "facebook", "nextdoor", "angi"],
        "keywords": ["cleaning service", "house cleaner", "maid service", "deep cleaning",
                      "commercial cleaning", "carpet cleaning", "janitorial",
                      "move out cleaning", "office cleaning"],
        "avg_job_value": 250,
        "lead_cpl_ceiling": 20,
        "seasons": ["all"],
        "urgency_triggers": [],
        "best_platform": "nextdoor",
        "conversion_rate": 0.18,
    },
    "pest_control": {
        "name": "Pest Control",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "nextdoor"],
        "keywords": ["pest control", "exterminator", "bug spray", "termite",
                      "rodent removal", "bed bugs", "ant control", "mosquito"],
        "avg_job_value": 350,
        "lead_cpl_ceiling": 28,
        "seasons": ["spring", "summer"],
        "urgency_triggers": ["termite", "bed bugs", "infestation", "roaches"],
        "best_platform": "google_maps",
        "conversion_rate": 0.14,
    },
    "moving": {
        "name": "Moving",
        "platforms": ["google_maps", "yelp", "facebook", "nextdoor", "angi"],
        "keywords": ["movers", "moving company", "local moving", "long distance moving",
                      "apartment movers", "piano movers", "packing service"],
        "avg_job_value": 900,
        "lead_cpl_ceiling": 35,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": ["last minute move", "urgent move"],
        "best_platform": "google_maps",
        "conversion_rate": 0.10,
    },
    # === FOUNDATION & STRUCTURE (NAICS 2381) ===
    "concrete": {
        "name": "Concrete",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "facebook"],
        "keywords": ["concrete contractor", "concrete driveway", "concrete patio",
                      "stamped concrete", "concrete foundation", "concrete slab",
                      "sidewalk repair", "concrete pouring"],
        "avg_job_value": 2200,
        "lead_cpl_ceiling": 60,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": ["cracked foundation", "sinking slab"],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.09,
    },
    "masonry": {
        "name": "Masonry",
        "platforms": ["google_maps", "homeadvisor", "yelp", "nextdoor", "houzz"],
        "keywords": ["masonry contractor", "brick repair", "stone work", "retaining wall",
                      "brick driveway", "stone veneer", "mortar repair", "chimney repair"],
        "avg_job_value": 2800,
        "lead_cpl_ceiling": 65,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": ["crumbling brick", "leaning wall"],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.08,
    },
    "siding": {
        "name": "Siding",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "houzz"],
        "keywords": ["siding contractor", "vinyl siding", "fiber cement siding",
                      "wood siding", "siding repair", "siding installation",
                      "hardie board", "exterior siding"],
        "avg_job_value": 4500,
        "lead_cpl_ceiling": 90,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": ["siding damage", "hole in siding"],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.07,
    },
    "framing": {
        "name": "Framing",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp"],
        "keywords": ["framing contractor", "wall framing", "roof framing",
                      "wood framing", "steel framing", "rough carpentry",
                      "structural framing"],
        "avg_job_value": 3500,
        "lead_cpl_ceiling": 75,
        "seasons": ["all"],
        "urgency_triggers": [],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.07,
    },
    "glass_and_glazing": {
        "name": "Glass & Glazing",
        "platforms": ["google_maps", "yelp", "nextdoor", "homeadvisor"],
        "keywords": ["glass contractor", "window glass replacement", "shower glass",
                      "glass door", "storefront glass", "custom mirrors",
                      "glass repair", "storefront glazing"],
        "avg_job_value": 600,
        "lead_cpl_ceiling": 30,
        "seasons": ["all"],
        "urgency_triggers": ["broken window", "shattered glass", "emergency glass"],
        "best_platform": "google_maps",
        "conversion_rate": 0.11,
    },
    # === BUILDING FINISHING (NAICS 2383) ===
    "drywall": {
        "name": "Drywall & Insulation",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "nextdoor"],
        "keywords": ["drywall contractor", "drywall repair", "drywall installation",
                      "insulation contractor", "blown insulation", "spray foam",
                      "drywall finishing", "mudding and taping"],
        "avg_job_value": 1200,
        "lead_cpl_ceiling": 40,
        "seasons": ["all"],
        "urgency_triggers": ["hole in wall", "water damaged drywall"],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.10,
    },
    "flooring": {
        "name": "Flooring",
        "platforms": ["google_maps", "yelp", "homeadvisor", "houzz", "angi"],
        "keywords": ["flooring contractor", "hardwood flooring", "carpet installation",
                      "vinyl plank flooring", "tile flooring", "floor refinishing",
                      "laminate flooring", "floor repair"],
        "avg_job_value": 2000,
        "lead_cpl_ceiling": 50,
        "seasons": ["all"],
        "urgency_triggers": [],
        "best_platform": "houzz",
        "conversion_rate": 0.12,
    },
    "tile": {
        "name": "Tile & Terrazzo",
        "platforms": ["google_maps", "houzz", "yelp", "homeadvisor", "angi"],
        "keywords": ["tile contractor", "tile installation", "backsplash tile",
                      "bathroom tile", "kitchen tile", "terrazzo flooring",
                      "tile repair", "grout repair"],
        "avg_job_value": 1500,
        "lead_cpl_ceiling": 45,
        "seasons": ["all"],
        "urgency_triggers": [],
        "best_platform": "houzz",
        "conversion_rate": 0.11,
    },
    "finish_carpentry": {
        "name": "Finish Carpentry",
        "platforms": ["google_maps", "houzz", "homeadvisor", "yelp", "nextdoor"],
        "keywords": ["finish carpenter", "crown molding", "baseboards", "custom cabinets",
                      "trim work", "built-in shelving", "wainscoting",
                      "door installation", "window casing"],
        "avg_job_value": 1800,
        "lead_cpl_ceiling": 50,
        "seasons": ["all"],
        "urgency_triggers": [],
        "best_platform": "houzz",
        "conversion_rate": 0.10,
    },
    # === HOME IMPROVEMENT & SPECIALTY ===
    "kitchen_and_bath": {
        "name": "Kitchen & Bath Remodeling",
        "platforms": ["google_maps", "houzz", "homeadvisor", "angi", "yelp"],
        "keywords": ["kitchen remodel", "bathroom remodel", "kitchen renovation",
                      "bathroom renovation", "cabinet refacing", "countertop installation",
                      "vanity installation", "shower remodel"],
        "avg_job_value": 12000,
        "lead_cpl_ceiling": 150,
        "seasons": ["all"],
        "urgency_triggers": [],
        "best_platform": "houzz",
        "conversion_rate": 0.05,
    },
    "deck_and_fence": {
        "name": "Deck & Fence",
        "platforms": ["google_maps", "homeadvisor", "yelp", "nextdoor", "facebook"],
        "keywords": ["deck builder", "deck repair", "fence installation", "fence repair",
                      "wood deck", "composite deck", "privacy fence", "chain link fence",
                      "deck staining", "porch builder"],
        "avg_job_value": 3000,
        "lead_cpl_ceiling": 60,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": ["rotten deck", "fallen fence"],
        "best_platform": "nextdoor",
        "conversion_rate": 0.09,
    },
    "gutter": {
        "name": "Gutter Services",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "nextdoor"],
        "keywords": ["gutter cleaning", "gutter installation", "gutter repair",
                      "seamless gutters", "leaf guard", "downspout repair",
                      "gutter guard", "gutter replacement"],
        "avg_job_value": 400,
        "lead_cpl_ceiling": 25,
        "seasons": ["spring", "fall"],
        "urgency_triggers": ["clogged gutter", "gutter leak", "water damage"],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.14,
    },
    "window_replacement": {
        "name": "Window Replacement",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "houzz"],
        "keywords": ["window replacement", "window installation", "energy efficient windows",
                      "double pane windows", "casement windows", "bay windows",
                      "window repair", "storm windows"],
        "avg_job_value": 3500,
        "lead_cpl_ceiling": 80,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": ["broken window", "drafty windows"],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.07,
    },
    "tree_service": {
        "name": "Tree Service",
        "platforms": ["google_maps", "yelp", "nextdoor", "facebook", "homeadvisor"],
        "keywords": ["tree service", "tree trimming", "tree removal", "stump grinding",
                      "tree pruning", "arborist", "storm cleanup", "lot clearing"],
        "avg_job_value": 700,
        "lead_cpl_ceiling": 35,
        "seasons": ["all"],
        "urgency_triggers": ["fallen tree", "emergency tree removal", "storm damage"],
        "best_platform": "nextdoor",
        "conversion_rate": 0.13,
    },
    "pool_service": {
        "name": "Pool Service",
        "platforms": ["google_maps", "yelp", "nextdoor", "facebook", "homeadvisor"],
        "keywords": ["pool service", "pool cleaning", "pool repair", "pool maintenance",
                      "pool opening", "pool closing", "pool heater repair",
                      "pool pump repair", "pool filter"],
        "avg_job_value": 300,
        "lead_cpl_ceiling": 25,
        "seasons": ["spring", "summer"],
        "urgency_triggers": ["green pool", "pool leak", "broken pump"],
        "best_platform": "nextdoor",
        "conversion_rate": 0.16,
    },
    # === RESTORATION & ENVIRONMENTAL ===
    "water_damage_restoration": {
        "name": "Water Damage Restoration",
        "platforms": ["google_maps", "homeadvisor", "yelp", "facebook", "nextdoor"],
        "keywords": ["water damage restoration", "flood cleanup", "water extraction",
                      "basement flooding", "water removal", "dry out service",
                      "mold remediation", "flood repair"],
        "avg_job_value": 2500,
        "lead_cpl_ceiling": 70,
        "seasons": ["all"],
        "urgency_triggers": ["burst pipe", "flood", "water leak", "basement flood", "emergency"],
        "best_platform": "google_maps",
        "conversion_rate": 0.08,
    },
    "fire_damage_restoration": {
        "name": "Fire & Smoke Restoration",
        "platforms": ["google_maps", "homeadvisor", "yelp", "angi"],
        "keywords": ["fire damage restoration", "smoke damage repair", "soot removal",
                      "fire cleanup", "fire repair", "structure fire cleaning",
                      "odor removal", "fire restoration company"],
        "avg_job_value": 5000,
        "lead_cpl_ceiling": 100,
        "seasons": ["all"],
        "urgency_triggers": ["fire damage", "smoke damage", "house fire", "structure fire"],
        "best_platform": "google_maps",
        "conversion_rate": 0.06,
    },
    "mold_removal": {
        "name": "Mold Inspection & Removal",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "nextdoor"],
        "keywords": ["mold inspection", "mold removal", "mold remediation", "black mold",
                      "mold testing", "mold abatement", "toxic mold", "mold treatment"],
        "avg_job_value": 1800,
        "lead_cpl_ceiling": 55,
        "seasons": ["all"],
        "urgency_triggers": ["black mold", "toxic mold", "mold infestation"],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.09,
    },
    # === HOME ENERGY & UTILITY ===
    "solar_installation": {
        "name": "Solar Installation",
        "platforms": ["google_maps", "homeadvisor", "yelp", "facebook", "angi"],
        "keywords": ["solar panel installation", "solar energy", "rooftop solar",
                      "solar power", "solar installer", "residential solar",
                      "battery backup", "solar system"],
        "avg_job_value": 15000,
        "lead_cpl_ceiling": 200,
        "seasons": ["all"],
        "urgency_triggers": [],
        "best_platform": "google_maps",
        "conversion_rate": 0.04,
    },
    "water_treatment": {
        "name": "Water Treatment",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "nextdoor"],
        "keywords": ["water softener", "water filtration", "reverse osmosis",
                      "whole house water filter", "water treatment system",
                      "well water filtration", "iron filter", "water testing"],
        "avg_job_value": 1200,
        "lead_cpl_ceiling": 45,
        "seasons": ["all"],
        "urgency_triggers": ["bad water", "hard water", "smelly water"],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.10,
    },
    "septic": {
        "name": "Septic Services",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "nextdoor"],
        "keywords": ["septic tank pumping", "septic repair", "septic installation",
                      "septic inspection", "drain field repair", "septic cleaning",
                      "septic system", "cesspool service"],
        "avg_job_value": 600,
        "lead_cpl_ceiling": 35,
        "seasons": ["all"],
        "urgency_triggers": ["septic backup", "septic smell", "septic emergency", "raw sewage"],
        "best_platform": "google_maps",
        "conversion_rate": 0.12,
    },
    "well_drilling": {
        "name": "Well Drilling",
        "platforms": ["google_maps", "homeadvisor", "yelp", "angi"],
        "keywords": ["well drilling", "water well", "well pump repair", "well installation",
                      "well service", "well inspection", "pump replacement", "well testing"],
        "avg_job_value": 4000,
        "lead_cpl_ceiling": 80,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": ["no water", "well pump failure", "well dry"],
        "best_platform": "google_maps",
        "conversion_rate": 0.07,
    },
    # === SPECIALTY SERVICES ===
    "chimney": {
        "name": "Chimney & Fireplace",
        "platforms": ["google_maps", "homeadvisor", "yelp", "nextdoor", "angi"],
        "keywords": ["chimney sweep", "chimney repair", "chimney cleaning", "fireplace repair",
                      "chimney inspection", "chimney liner", "chimney cap",
                      "masonry chimney", "gas fireplace"],
        "avg_job_value": 350,
        "lead_cpl_ceiling": 30,
        "seasons": ["fall", "winter"],
        "urgency_triggers": ["chimney leak", "smoke in house", "chimney fire"],
        "best_platform": "google_maps",
        "conversion_rate": 0.13,
    },
    "driveway_paving": {
        "name": "Driveway Paving",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "nextdoor"],
        "keywords": ["driveway paving", "asphalt driveway", "concrete driveway",
                      "driveway sealcoating", "driveway repair", "parking lot paving",
                      "paving contractor", "asphalt repair"],
        "avg_job_value": 2500,
        "lead_cpl_ceiling": 65,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": ["cracked driveway", "pothole"],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.08,
    },
    "carpet_cleaning": {
        "name": "Carpet Cleaning",
        "platforms": ["google_maps", "yelp", "nextdoor", "facebook", "angi"],
        "keywords": ["carpet cleaning", "upholstery cleaning", "rug cleaning",
                      "steam cleaning", "carpet shampoo", "tile and grout cleaning",
                      "area rug cleaning", "commercial carpet cleaning"],
        "avg_job_value": 200,
        "lead_cpl_ceiling": 18,
        "seasons": ["all"],
        "urgency_triggers": [],
        "best_platform": "nextdoor",
        "conversion_rate": 0.19,
    },
    "handyman": {
        "name": "Handyman Services",
        "platforms": ["google_maps", "nextdoor", "yelp", "facebook", "angi"],
        "keywords": ["handyman", "home repair", "handyman services", "home maintenance",
                      "odd jobs", "furniture assembly", "drywall repair",
                      "caulking", "general handyman"],
        "avg_job_value": 250,
        "lead_cpl_ceiling": 20,
        "seasons": ["all"],
        "urgency_triggers": ["emergency repair"],
        "best_platform": "nextdoor",
        "conversion_rate": 0.20,
    },
    # === HOME SECURITY & SAFETY ===
    "locksmith": {
        "name": "Locksmith",
        "platforms": ["google_maps", "yelp", "nextdoor", "facebook"],
        "keywords": ["locksmith", "lock repair", "key duplication", "emergency locksmith",
                      "lock installation", "safe unlocking", "rekey", "smart lock",
                      "car lockout", "home lockout"],
        "avg_job_value": 200,
        "lead_cpl_ceiling": 20,
        "seasons": ["all"],
        "urgency_triggers": ["locked out", "emergency locksmith", "broken key", "lockout"],
        "best_platform": "google_maps",
        "conversion_rate": 0.22,
    },
    "security_system": {
        "name": "Security Systems",
        "platforms": ["google_maps", "homeadvisor", "yelp", "nextdoor", "facebook"],
        "keywords": ["home security", "security system installation", "alarm system",
                      "security camera", "smart home security", "doorbell camera",
                      "surveillance system", "access control", "monitoring service"],
        "avg_job_value": 800,
        "lead_cpl_ceiling": 50,
        "seasons": ["all"],
        "urgency_triggers": ["break in", "burglary", "security concern"],
        "best_platform": "google_maps",
        "conversion_rate": 0.09,
    },
    "fire_protection": {
        "name": "Fire Protection",
        "platforms": ["google_maps", "yelp", "homeadvisor", "angi"],
        "keywords": ["fire alarm installation", "fire extinguisher service", "sprinkler system",
                      "fire protection contractor", "smoke detector", "fire suppression",
                      "fire safety inspection", "commercial fire protection"],
        "avg_job_value": 700,
        "lead_cpl_ceiling": 40,
        "seasons": ["all"],
        "urgency_triggers": ["fire code violation", "faulty alarm"],
        "best_platform": "google_maps",
        "conversion_rate": 0.10,
    },
    # === DEMOLITION & HAULING ===
    "dumpster_rental": {
        "name": "Dumpster Rental & Junk Removal",
        "platforms": ["google_maps", "yelp", "nextdoor", "facebook", "homeadvisor"],
        "keywords": ["dumpster rental", "junk removal", "roll off dumpster",
                      "waste disposal", "debris removal", "construction dumpster",
                      "trash hauling", "bulky item pickup"],
        "avg_job_value": 350,
        "lead_cpl_ceiling": 25,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": [],
        "best_platform": "google_maps",
        "conversion_rate": 0.15,
    },
    "demolition": {
        "name": "Demolition Services",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp"],
        "keywords": ["demolition contractor", "house demolition", "interior demolition",
                      "concrete demolition", "building demolition", "selective demolition",
                      "site clearing", "excavation"],
        "avg_job_value": 3000,
        "lead_cpl_ceiling": 75,
        "seasons": ["all"],
        "urgency_triggers": [],
        "best_platform": "homeadvisor",
        "conversion_rate": 0.07,
    },
    # === APPLIANCE & HOME SYSTEMS ===
    "appliance_repair": {
        "name": "Appliance Repair",
        "platforms": ["google_maps", "yelp", "nextdoor", "facebook", "homeadvisor"],
        "keywords": ["appliance repair", "refrigerator repair", "washer repair",
                      "dryer repair", "oven repair", "dishwasher repair",
                      "stove repair", "appliance service"],
        "avg_job_value": 200,
        "lead_cpl_ceiling": 20,
        "seasons": ["all"],
        "urgency_triggers": ["broken fridge", "broken washer", "appliance emergency"],
        "best_platform": "google_maps",
        "conversion_rate": 0.18,
    },
    "garage_door": {
        "name": "Garage Door Services",
        "platforms": ["google_maps", "homeadvisor", "angi", "yelp", "nextdoor"],
        "keywords": ["garage door repair", "garage door installation", "garage door opener",
                      "garage door spring", "garage door replacement", "garage door panel",
                      "garage door motor", "overhead door"],
        "avg_job_value": 400,
        "lead_cpl_ceiling": 30,
        "seasons": ["all"],
        "urgency_triggers": ["garage door stuck", "broken spring", "door won't open"],
        "best_platform": "google_maps",
        "conversion_rate": 0.14,
    },
    "pressure_washing": {
        "name": "Pressure Washing",
        "platforms": ["google_maps", "yelp", "nextdoor", "facebook", "homeadvisor"],
        "keywords": ["pressure washing", "power washing", "house washing", "driveway cleaning",
                      "deck cleaning", "concrete cleaning", "roof washing",
                      "soft washing", "commercial pressure washing"],
        "avg_job_value": 300,
        "lead_cpl_ceiling": 22,
        "seasons": ["spring", "summer", "fall"],
        "urgency_triggers": [],
        "best_platform": "nextdoor",
        "conversion_rate": 0.17,
    },
    # === REAL ESTATE & LAND DEVELOPMENT ===
    "land_developer": {
        "name": "Land Developer",
        "platforms": ["linkedin", "apollo", "google_maps", "zillow", "loopnet", "landwatch", "homeadvisor", "yelp", "facebook"],
        "keywords": [
            "land developer", "land acquisition", "land buyer", "property developer",
            "real estate developer", "lot builder", "subdivision developer",
            "land purchaser", "developer buying land", "land investment",
            "residential land development", "commercial land development",
            "master planned community", "tract home builder", "home builder",
            "VP land acquisition", "director of land acquisition",
            "land acquisition manager", "VP of development", "director of development",
            "chief development officer", "land entitlement", "VP acquisitions",
            "director of acquisitions", "land entitlement manager",
            "raw land buyer", "parcel acquisition", "site selection director",
            "entitlement consultant", "land banker", "land flipper",
            "infill developer", "spec home builder", "custom home builder",
            "residential subdivision", "mixed use developer",
            "commercial developer", "industrial park developer",
        ],
        "avg_job_value": 50000,
        "lead_cpl_ceiling": 250,
        "seasons": ["all"],
        "urgency_triggers": ["land for sale", "zoning change", "expiring option", "entitlement approved", "parcel available"],
        "best_platform": "apollo",
        "conversion_rate": 0.03,
        "person_titles": [
            "VP Land Acquisition", "Director of Land Acquisition", "Land Acquisition Manager",
            "VP of Development", "Director of Development", "Chief Development Officer",
            "VP Acquisitions", "Director of Acquisitions", "Land Buyer",
            "VP Real Estate", "Director of Real Estate", "Land Entitlement Manager",
            "President", "CEO", "Owner", "Managing Partner",
        ],
    },
}


def list_trades() -> list[dict]:
    return [
        {
            "trade_id": trade_id,
            "name": config["name"],
            "best_platform": config["best_platform"],
            "platforms": config["platforms"],
            "avg_job_value": config["avg_job_value"],
            "conversion_rate": config["conversion_rate"],
        }
        for trade_id, config in TRADE_REGISTRY.items()
    ]


def get_trade_config(trade_id: str) -> dict | None:
    return TRADE_REGISTRY.get(trade_id)
