"""CRM + Support + Help-desk integrations."""
from ..base import manifest, AuthScheme

MANIFESTS = [
    manifest("hubspot", "https://api.hubapi.com",
        display="HubSpot", category="crm",
        auth=AuthScheme(kind="bearer", env_var="HUBSPOT_TOKEN"),
        actions={
            "contacts.list":    ("GET",  "/crm/v3/objects/contacts",
                                   ["limit", "after", "properties"]),
            "contact.get":      ("GET",  "/crm/v3/objects/contacts/{contactId}"),
            "contact.create":   ("POST", "/crm/v3/objects/contacts", [],
                                   ["properties"]),
            "contact.update":   ("PATCH","/crm/v3/objects/contacts/{contactId}",
                                   [], ["properties"]),
            "contact.delete":   ("DELETE","/crm/v3/objects/contacts/{contactId}"),
            "deals.list":       ("GET",  "/crm/v3/objects/deals"),
            "deal.create":      ("POST", "/crm/v3/objects/deals", [],
                                   ["properties", "associations"]),
            "companies.list":   ("GET",  "/crm/v3/objects/companies"),
            "company.create":   ("POST", "/crm/v3/objects/companies", [],
                                   ["properties"]),
            "search.contacts":  ("POST", "/crm/v3/objects/contacts/search", [],
                                   ["filterGroups", "sorts", "properties",
                                    "limit"]),
            "emails.send":      ("POST", "/marketing/v3/transactional/single-email/send",
                                   [], ["emailId", "message", "contactProperties"]),
        }, docs_url="https://developers.hubspot.com/docs/api/overview"),

    manifest("salesforce", "https://example.my.salesforce.com/services/data/v59.0",
        display="Salesforce", category="crm",
        auth=AuthScheme(kind="bearer", env_var="SALESFORCE_TOKEN"),
        actions={
            "query":          ("GET",  "/query", ["q"]),
            "object.create":  ("POST", "/sobjects/{object_name}", [], []),
            "object.update":  ("PATCH","/sobjects/{object_name}/{id}", [], []),
            "object.delete":  ("DELETE","/sobjects/{object_name}/{id}"),
            "object.get":     ("GET",  "/sobjects/{object_name}/{id}"),
            "describe":       ("GET",  "/sobjects/{object_name}/describe"),
        }, docs_url="https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest/"),

    manifest("pipedrive", "https://api.pipedrive.com/v1",
        display="Pipedrive", category="crm",
        auth=AuthScheme(kind="query", env_var="PIPEDRIVE_API_TOKEN",
                          query_name="api_token"),
        actions={
            "deals.list":      ("GET",  "/deals", ["status", "limit"]),
            "deal.create":     ("POST", "/deals", [],
                                  ["title", "value", "currency", "person_id"]),
            "persons.list":    ("GET",  "/persons"),
            "person.create":   ("POST", "/persons", [],
                                  ["name", "email", "phone"]),
            "activities.list": ("GET",  "/activities"),
            "activity.create": ("POST", "/activities", [],
                                  ["subject", "type", "due_date"]),
        }, docs_url="https://developers.pipedrive.com/docs/api/v1"),

    manifest("zoho_crm", "https://www.zohoapis.com/crm/v3",
        display="Zoho CRM", category="crm",
        auth=AuthScheme(kind="header", env_var="ZOHO_OAUTH_TOKEN",
                          header_name="Authorization",
                          bearer_prefix="Zoho-oauthtoken "),
        actions={
            "leads.list":   ("GET",  "/Leads"),
            "lead.create":  ("POST", "/Leads", [], ["data"]),
            "deals.list":   ("GET",  "/Deals"),
            "contacts.list":("GET",  "/Contacts"),
        }, docs_url="https://www.zoho.com/crm/developer/docs/api/v3/"),

    manifest("close", "https://api.close.com/api/v1",
        display="Close.com", category="crm",
        auth=AuthScheme(kind="basic", env_var="CLOSE_AUTH"),
        actions={
            "leads.list":   ("GET",  "/lead/"),
            "lead.create":  ("POST", "/lead/", [],
                              ["name", "url", "contacts"]),
            "opportunities":("GET",  "/opportunity/"),
        }, docs_url="https://developer.close.com/"),

    manifest("apollo_io", "https://api.apollo.io/v1",
        display="Apollo.io", category="crm",
        auth=AuthScheme(kind="query", env_var="APOLLO_API_KEY",
                          query_name="api_key"),
        actions={
            "people.search":   ("POST", "/mixed_people/search", [],
                                  ["q_keywords", "person_titles", "page"]),
            "organizations.search":("POST", "/mixed_companies/search", [],
                                       ["q_keywords", "page"]),
            "people.match":    ("POST", "/people/match", [],
                                  ["first_name", "last_name", "email",
                                   "organization_name"]),
        }, docs_url="https://apolloio.github.io/apollo-api-docs/"),

    manifest("clearbit", "https://person.clearbit.com/v2",
        display="Clearbit", category="crm",
        auth=AuthScheme(kind="bearer", env_var="CLEARBIT_KEY"),
        actions={
            "person.find":  ("GET",  "/people/find", ["email"]),
            "company.find": ("GET",  "/companies/find", ["domain"]),
        }, docs_url="https://clearbit.com/docs"),

    # ---- Support / Helpdesk ----

    manifest("intercom", "https://api.intercom.io",
        display="Intercom", category="support",
        auth=AuthScheme(kind="bearer", env_var="INTERCOM_TOKEN"),
        actions={
            "contacts.list":   ("GET",  "/contacts"),
            "contact.create":  ("POST", "/contacts", [],
                                  ["email", "name", "phone", "external_id"]),
            "conversations":   ("GET",  "/conversations"),
            "message.reply":   ("POST",
                                  "/conversations/{conversation_id}/reply", [],
                                  ["message_type", "type", "admin_id", "body"]),
            "tags.list":       ("GET",  "/tags"),
        }, docs_url="https://developers.intercom.com/intercom-api-reference"),

    manifest("zendesk", "https://example.zendesk.com/api/v2",
        display="Zendesk", category="support",
        auth=AuthScheme(kind="basic", env_var="ZENDESK_AUTH"),
        actions={
            "tickets.list":   ("GET",  "/tickets.json"),
            "ticket.get":     ("GET",  "/tickets/{id}.json"),
            "ticket.create":  ("POST", "/tickets.json", [], ["ticket"]),
            "ticket.update":  ("PUT",  "/tickets/{id}.json", [], ["ticket"]),
            "users.list":     ("GET",  "/users.json"),
            "users.search":   ("GET",  "/users/search.json", ["query"]),
            "macros.list":    ("GET",  "/macros.json"),
        }, docs_url="https://developer.zendesk.com/api-reference/"),

    manifest("freshdesk", "https://example.freshdesk.com/api/v2",
        display="Freshdesk", category="support",
        auth=AuthScheme(kind="basic", env_var="FRESHDESK_AUTH"),
        actions={
            "tickets.list":  ("GET",  "/tickets"),
            "ticket.get":    ("GET",  "/tickets/{id}"),
            "ticket.create": ("POST", "/tickets", [],
                                ["subject", "description", "email", "priority",
                                 "status"]),
            "contacts.list": ("GET",  "/contacts"),
        }, docs_url="https://developers.freshdesk.com/api/"),

    manifest("helpscout", "https://api.helpscout.net/v2",
        display="Help Scout", category="support",
        auth=AuthScheme(kind="bearer", env_var="HELPSCOUT_TOKEN"),
        actions={
            "conversations.list":  ("GET",  "/conversations"),
            "conversation.create": ("POST", "/conversations", [],
                                       ["type", "subject", "customer",
                                        "mailboxId", "status", "threads"]),
        }, docs_url="https://developer.helpscout.com/mailbox-api/"),

    manifest("crisp", "https://api.crisp.chat/v1",
        display="Crisp", category="support",
        auth=AuthScheme(kind="basic", env_var="CRISP_AUTH"),
        actions={
            "website.info":    ("GET",  "/website/{website_id}"),
            "conversations":   ("GET",
                                  "/website/{website_id}/conversations/{page}"),
            "send.message":    ("POST",
                                  "/website/{website_id}/conversation/"
                                  "{session_id}/message", [], ["type", "from",
                                                                "origin", "content"]),
        }, docs_url="https://docs.crisp.chat/api/v1/"),

    manifest("drift", "https://driftapi.com",
        display="Drift", category="support",
        auth=AuthScheme(kind="bearer", env_var="DRIFT_TOKEN"),
        actions={
            "contacts":         ("GET",  "/contacts"),
            "contact.create":   ("POST", "/contacts", [], ["attributes"]),
            "conversations":    ("GET",  "/conversations"),
        }, docs_url="https://devdocs.drift.com"),

    manifest("front", "https://api2.frontapp.com",
        display="Front", category="support",
        auth=AuthScheme(kind="bearer", env_var="FRONT_TOKEN"),
        actions={
            "inboxes":      ("GET",  "/inboxes"),
            "conversations":("GET",  "/conversations"),
            "messages.send":("POST", "/channels/{channel_id}/messages", [],
                              ["to", "subject", "body"]),
        }, docs_url="https://dev.frontapp.com/reference"),
]
